#version: '3.8'

services:
  web:
    build: 
      context: ./WebApp  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=your_secret_key
      - MONGO_URI=mongodb+srv://ql2138:W2L26WaXhb7AufjU@cluster0.la97a.mongodb.net/pj5expense?retryWrites=true&w=majority&appName=Cluster0

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
