name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        # Here you would add commands to run your tests
        echo "No tests specified"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to DigitalOcean Droplet
      env:
        DO_IP: ${{ secrets.DO_IP }} 
        DO_USER: ${{ secrets.DO_USER }}
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
      run: |
        echo "$DO_SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $DO_USER@$DO_IP "sudo systemctl stop flask_app"
        scp -i key.pem -r * $DO_USER@$DO_IP:/home/$DO_USER/flask_app/
        ssh -i key.pem $DO_USER@$DO_IP "cd /home/$DO_USER/flask_app && python3 -m pip install -r requirements.txt"
        ssh -i key.pem $DO_USER@$DO_IP "sudo systemctl start flask_app"
        rm key.pem
